services:
  caddy:
    container_name: caddy
    image: caddy:2
    env_file: ../.env
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ../Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
